### ISSUE TITLE
Questions about AWS account and temp file for image

### ISSUE THREAD

**Issue by ercbk** [BMGhack/BMGPetBot#7]
I'm creating my own twitterbot for Louisville Metro Animal Services in R. Have a few questions if you have the time.

1. Whose account did you use for the AWS Lambda Function? ...Animals services or City of Bloomington or BMGHack or someone's personal account?

2. If you got a free tier account, do you know what happens when that expires. I know (at least I think I know) the function stays active and you get the same invocation and GB/s rates but do you still have access to change or update the code if something happens?

3. "1/20/2018 SDC don't save image to temp file!" from petbot.py. Assuming you didn't create a temp file, how did you tweet the image!? Twitter doesn't allow image links to display images so if I can't create a temp file, I'm stumped.

4. Out of curiosity, what does SDC stand for? lol

Thanks for your time and also the code!

**Comment by sdcharle** [comment]
Hey Eric, thank for reaching out! Louisville's a pretty cool town, will be glad to help if I can. To answer your questions:

1. Actually, a the moment, my personal account. Me being sdcharle, SDC being my initials (answer to 4) - Stephen D. Charlesworth) - I will probably coordinate some sort of hand-off to a more official City account down the line.

2. I hadn't considered that, to be honest. It looks like Lambda falls under 'non-expiring offers' according to this https://aws.amazon.com/free/ - so I think we should be fine.

3. On this one there's a function 'get_image_blob(url)' that's basically pulling in the whole image and then base64 encoding it and all that, and then wrapping it in 'io.BytesIO' which is passed to the api.update_with_media call as the file argument. So, basically, it's pulled into memory.

Let me know how things go and if you have other questions feel free to ask.]

**Comment by sdcharle** [comment]
You good? I'm going to close the issue unless you have other questions.

**Comment by ercbk** [comment]
I'm sorry. I forgot to get back to you. Everything with the bot turned out well (@erbo_exp_bot). I'm still communicating with the shelter through a third party so it's not connected to their account yet. But yeah you can close it and thanks again for your help.
