### ISSUE TITLE
Tweet formatting

### ISSUE THREAD

**Issue by rbdietz** [BMGhack/BMGPetBot#8]
Any chance of updating this twitter bot to something like this instead of the stacked variables in the attached image?

Adopt Snowball, a very large American female rabbit, age 6 years 1 month! #rabbit [etc]
Adopt [Name], a [size] [Breed] [sex] [species], age [age]! #[species] [etc]

<img width="453" alt="screen shot 2018-04-26 at 10 04 29 pm" src="https://user-images.githubusercontent.com/1135994/39557054-d8d85c4e-4e52-11e8-8865-59b5537e8c44.png">

**Comment by sdcharle** [comment]
Definitely doable. I was hewing close to the website format for v1 but it's definitely flexible.

I should be able to address in the near future.

**Comment by sdcharle** [comment]
I made some changes. What do you think? https://twitter.com/adopttodaybtown

**Comment by rbdietz** [comment]
This is great, thanks!!!





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by sdcharle** [comment]
Cool - I'll close this out then. Thanks.
